[package]
name = "client"
version = "0.1.0"
authors = ["Kirill Brazhnikov <agamemnon886@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.17.7"
linecount = "0.1.0"
chrono = "0.4.15"
